version: "3"

volumes:
  db-store:

services:
  db:
    image: mysql:8.0
    platform: 'linux/amd64' # M1チップ対応のため追記
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_ROOT_PASSWORD=root

  schemaspy:
    build: schemaspy
    volumes:
      - ./output:/output